require 'yt/collections/earnings'

module Yt
  module Associations
    # Provides methods which allows to access the earnings generated by a resource.
    #
    # YouTube resources with earning are: {Yt::Models::Channel channels}.
    module Earnings
      # @return [Float] the estimated earnings for one specific day in USD.
      # @param [Date or Time or DateTime or String] date The date to obtain
      #   the estimated earnings for. If +String+, must be Date-parseable.
      def earnings_on(date)
        earnings(from: date, to: date).values.first
      end

      # @return [Hash] the estimated earnings for a range of days. Each +key+ is a +Date+
      #   and each +value+ is a +Float+, representing estimated earnings in USD.
      # @param [Hash] options the range of days to get the earnings for.
      # @option options [Date or Time or DateTime or String] :since The start
      #   of the days range. If +String+, must be Date-parseable. Also aliased as *:from*.
      # @option options [Date or Time or DateTime or String] :until The end
      #   of the days range. If +String+, must be Date-parseable. Also aliased as *:to*.
      def earnings(options = {})
        from = options[:since] || options[:from] || 6.days.ago
        to = options[:until] || options[:to] || 2.days.ago
        range = Range.new *[from, to].map(&:to_date)

        Hash[*range.flat_map do |date|
          [date, (@earnings ||= {})[date] ||= range_earnings(range)[date]]
        end]
      end

    private

      def range_earnings(date_range)
        (@range_earnings ||= {})[date_range] ||= all_earnings.within date_range
      end

      def all_earnings
        Collections::Earnings.of self
      end
    end
  end
end